export { getLandingPageData } from "./service";
export type {
  LandingPageData,
  HeroSection,
  NavLink,
  TrustSignal,
  SocialProof,
  Testimonial,
  TestimonialsSection,
  TrustPartner,
  TrustPartnersSection,
  PricingPlan,
  PricingFeature,
  PricingSection,
  HowItWorksStep,
  HowItWorksSection,
  StatItem,
  StatsSection,
  FaqItem,
  FaqSection,
  CtaBannerSection,
  SocialLink,
  FooterColumn,
  FooterSection,
} from "./schema";
